### ISSUE TITLE
Can't compile with Kotlin 2.2.0

### ISSUE THREAD

**Issue by eygraber** [Foso/Ktorfit#870]
### Ktorfit version

2.5.2

### What happened and how can we reproduce this issue?

When I try to compile after updating Kotlin to 2.2.0 I get the following error:

```
e: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.declarations.IrValueParameter org.jetbrains.kotlin.ir.declarations.IrValueParameter.transform(org.jetbrains.kotlin.ir.visitors.IrElementTransformer, java.lang.Object)'
        at de.jensklingenberg.ktorfit.ElementTransformer.visitValueParameterNew(ElementTransformer.kt:18)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitValueParameter(IrElementTransformerVoidWithContext.kt:97)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitValueParameter(IrElementTransformerVoid.kt:51)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitValueParameter(IrElementTransformerVoid.kt:19)
        at org.jetbrains.kotlin.ir.declarations.IrValueParameter.accept(IrValueParameter.kt:136)
        at org.jetbrains.kotlin.ir.declarations.IrValueParameter.transform(IrValueParameter.kt:139)
        at org.jetbrains.kotlin.ir.declarations.IrValueParameter.transform(IrValueParameter.kt:21)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:295)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunction(IrElementTransformerVoid.kt:72)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunctionNew(IrElementTransformerVoidWithContext.kt:130)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:83)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:128)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:131)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:19)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:39)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:82)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:54)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClassNew(IrElementTransformerVoidWithContext.kt:126)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClass(IrElementTransformerVoidWithContext.kt:62)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:57)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:19)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrPackageFragment.transformChildren(IrPackageFragment.kt:31)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitPackageFragment(IrElementTransformerVoid.kt:146)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:160)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFileNew(IrElementTransformerVoidWithContext.kt:122)
        at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFile(IrElementTransformerVoidWithContext.kt:55)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:163)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:19)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:27)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:30)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:19)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transformChildren(IrModuleFragment.kt:46)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:102)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:107)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:19)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:36)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:39)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:33)
        at de.jensklingenberg.ktorfit.KtorfitIrGenerationExtension.generate(KtorfitIrGenerationExtension.kt:12)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:468)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:245)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:128)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize(convertToIr.kt:97)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize$default(convertToIr.kt:72)
        at org.jetbrains.kotlin.cli.jvm.compiler.legacy.pipeline.JvmCompilerPipelineKt.convertToIrAndActualizeForJvm(jvmCompilerPipeline.kt:109)
        at org.jetbrains.kotlin.cli.pipeline.jvm.JvmFir2IrPipelinePhase.executePhase(JvmFir2IrPipelinePhase.kt:26)
        at org.jetbrains.kotlin.cli.pipeline.jvm.JvmFir2IrPipelinePhase.executePhase(JvmFir2IrPipelinePhase.kt:17)
        at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:68)
        at org.jetbrains.kotlin.cli.pipeline.PipelinePhase.phaseBody(PipelinePhase.kt:58)
        at org.jetbrains.kotlin.config.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:102)
        at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
        at org.jetbrains.kotlin.config.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:53)
        at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.runPhasedPipeline(AbstractCliPipeline.kt:109)
        at org.jetbrains.kotlin.cli.pipeline.AbstractCliPipeline.execute(AbstractCliPipeline.kt:68)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:78)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecutePhased(K2JVMCompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:90)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:352)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerBase.runCompiler(IncrementalJvmCompilerRunnerBase.kt:175)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunnerBase.runCompiler(IncrementalJvmCompilerRunnerBase.kt:38)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:504)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:421)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:306)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:133)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:679)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1806)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

### What did you expect to happen?

Not to have any errors

**Comment by dawidhyzy** [comment]
Bumping KSP to `v2.2.0-2.0.2` doesn't resolve the issue either.

**Comment by silveryTitan** [comment]
When can we update the version to solve the problem?

**Comment by eygraber** [comment]
When the maintainer merges it and releases it.

**Comment by hmy65** [comment]
> Hi, i'm planning to release a new version at the weekend

@Foso 
Can me make this library not rely on kotlin version? I have no experience of build library, jusk curious:)

**Comment by silveryTitan** [comment]
@Foso Hi,Just a reminder, please do not release the ktor3.2 branch as it has a bug. The bug is: the variable naming in the SaveBody class uses spaces, causing compilation failure

**Comment by hmy65** [comment]
> [@Foso](https://github.com/Foso) Hi,Just a reminder, please do not release the ktor3.2 branch as it has a bug. The bug is: the variable naming in the SaveBody class uses spaces, causing compilation failure

@silveryTitan @Foso 
This issue can be easily fixed here: https://youtrack.jetbrains.com/issue/KTOR-8583#focus=Comments-27-12184056.0-0

There is no reason for newer version ktorfit to use old version ktor.

**Comment by AkesiSeli** [comment]
I am starting to think that JetBrains found the way to kill this library. Probably the best way is to use plain Ktor and implement "services" by hand (tedious I know but at least it does not rely on KSP or the compiler breaking compatibility with each and every release).

**Comment by dawidhyzy** [comment]
> I am starting to think that JetBrains found the way to kill this library. Probably the best way is to use plain Ktor and implement "services" by hand (tedious I know but at least it does not rely on KSP or the compiler breaking compatibility with each and every release).

Not at all. If you were to use Ktor v3.2.0 directly, you would face the same issue. I strongly believe that it is **not** in JetBrains's interest to kill this library.

**Comment by AkesiSeli** [comment]
I remember it being publicly recommended in some past editions of KotlinConf but it's never mentioned in the official docs.

Since not being able to update to Kotlin 2.2.0 also implies [being stuck with AGP8.7.2](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html#version-compatibility) and this is affecting me for several other issues, I am seriously considering the option to migrate away from this library. Why would plain Ktor (no annotation processing) be affected? Isn't this just an incompatibility with KSP?

**Comment by hmy65** [comment]
> Yeah, let's not exaggerate here.
> 
> This is an open source project which y'all get for free. Quit complaining, and constantly asking for updates. If you want to write all of the service definitions yourself, then go ahead!

In other words, this reflects that the library is used in production in many apps.

**Comment by chrisbanes** [comment]
> > Yeah, let's not exaggerate here.
> > 
> > This is an open source project which y'all get for free. Quit complaining, and constantly asking for updates. If you want to write all of the service definitions yourself, then go ahead!
> 
> In other words, this reflects that the library is used in production in many apps.

That doesn't matter. Are you paying for support? Are you paying for maintenance? I very much doubt it, therefore you have zero right to expect *anything*.

The worst here is that you have to wait to be able to update to Kotlin 2.2. Just be patient.

**Comment by hmy65** [comment]
> > > Yeah, let's not exaggerate here.
> > > This is an open source project which y'all get for free. Quit complaining, and constantly asking for updates. If you want to write all of the service definitions yourself, then go ahead!
> > 
> > 
> > In other words, this reflects that the library is used in production in many apps.
> 
> That doesn't matter. Are you paying for support? Are you paying for maintenance? I very much doubt it, therefore you have zero right to expect _anything_.
> 
> The worst here is that you have to wait to be able to update to Kotlin 2.2. Just be patient.

You clearly exaggerate my point. If I can build a library used by many others no matter in production or not, I will be really happy. I don't really care if anyone push me to update, I can ignore just like other works.

**Comment by AkesiSeli** [comment]
I am a maintainer of open source projects myself (I have to deal with user requests, who often do not even understand the amount of work required behind what they are asking for). If I receive crazy requests I answer in the most polite way, after all even reporting bugs they are helping me, or just ignore them until I find some spare time to address them.

Just once in my memory (but it was not directed specifically to anyone, just a general consideration), I remember I told "people can also use an alternative" for a specific feature I was not planning to add support for.

**Comment by Foso** [comment]
Thank you for reporting, i'm working on it
